import type { VercelRequest, VercelResponse } from "@vercel/node";
import express from "express";
import { ExpressAdapter } from "@nestjs/platform-express";
import { NestFactory } from "@nestjs/core";
import { HttpStatus, ValidationPipe } from "@nestjs/common";
import * as cookieParser from "cookie-parser";
import * as useragent from "express-useragent";
import helmet from "helmet";

let cachedServer: ReturnType<typeof express> | null = null;

async function createServer() {
  const expressApp = express();

  // Import compiled Nest module + utilities from dist (generated by `nest build`).
  // This avoids TS path-alias resolution issues in the Vercel runtime.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { AppModule } = require("../dist/app.module");
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { GlobalExceptionFilter } = require("../dist/utils/filters/global-exception.filter");
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { ResponseFormInterceptor } = require("../dist/utils/interceptors/response-form.interceptor");

  const nestApp = await NestFactory.create(AppModule, new ExpressAdapter(expressApp));

  nestApp.enableCors();
  nestApp.use(cookieParser());
  nestApp.use(useragent.express());
  nestApp.use(helmet());

  nestApp.useGlobalFilters(new GlobalExceptionFilter());
  nestApp.useGlobalInterceptors(new ResponseFormInterceptor());
  nestApp.useGlobalPipes(
    new ValidationPipe({
      errorHttpStatusCode: HttpStatus.NOT_ACCEPTABLE,
      whitelist: true,
      validateCustomDecorators: true
    })
  );

  await nestApp.init();

  return expressApp;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (!cachedServer) {
    cachedServer = await createServer();
  }

  return cachedServer(req, res);
}
